from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Protocol

from odds_scanner.domain import BetStatus, Event, OddsSnapshot, Quote, TrackedBet


class QuoteRepository(Protocol):
    def save_snapshot(self, snapshot: OddsSnapshot) -> None: ...

    def load_quotes_since(self, since: datetime) -> tuple[Quote, ...]: ...

    def load_latest_quotes(self, provider_id: str) -> tuple[Quote, ...]: ...

    def load_events(self) -> tuple[Event, ...]: ...

    def save_setting(self, key: str, value: str) -> None: ...

    def load_settings(self) -> dict[str, str]: ...

    def add_bet(self, bet: TrackedBet) -> int: ...

    def list_bets(self) -> tuple[TrackedBet, ...]: ...

    def update_bet(
        self, bet_id: int, status: BetStatus, profit_loss: Decimal | None
    ) -> None: ...

    def watched_event_ids(self) -> frozenset[str]: ...

    def set_event_watched(self, event_id: str, watched: bool, created_at: datetime) -> None: ...
